"""Baseline Schema v2.1

Revision ID: 892810d42bbe
Revises: 
Create Date: 2026-01-29 22:02:04.798256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892810d42bbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('conflicts', sa.Integer(), nullable=False),
    sa.Column('not_found', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_status'), ['status'], unique=False)

    op.create_table('issuers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('nomisma_id', sa.String(length=50), nullable=False),
    sa.Column('issuer_type', sa.String(length=20), nullable=False),
    sa.Column('reign_start', sa.Integer(), nullable=True),
    sa.Column('reign_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issuers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuers_canonical_name'), ['canonical_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_issuers_nomisma_id'), ['nomisma_id'], unique=False)

    op.create_table('mints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=100), nullable=False),
    sa.Column('nomisma_id', sa.String(length=50), nullable=False),
    sa.Column('active_from', sa.Integer(), nullable=True),
    sa.Column('active_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mints_canonical_name'), ['canonical_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_mints_nomisma_id'), ['nomisma_id'], unique=False)

    op.create_table('monograms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('vector_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monograms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monograms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monograms_label'), ['label'], unique=False)

    op.create_table('reference_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('local_ref', sa.String(length=100), nullable=False),
    sa.Column('local_ref_normalized', sa.String(length=100), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('variant', sa.String(length=10), nullable=True),
    sa.Column('mint', sa.String(length=30), nullable=True),
    sa.Column('supplement', sa.String(length=10), nullable=True),
    sa.Column('collection', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_types_id'), ['id'], unique=False)

    op.create_table('vocab_cache',
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('vocab_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('vocab_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('nomisma_uri', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocab_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_terms_vocab_type'), ['vocab_type'], unique=False)

    op.create_table('coins_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metal', sa.String(length=50), nullable=False),
    sa.Column('weight_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('diameter_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('die_axis', sa.Integer(), nullable=True),
    sa.Column('issuer', sa.String(length=100), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('mint', sa.String(length=100), nullable=True),
    sa.Column('mint_id', sa.Integer(), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('issuer_term_id', sa.Integer(), nullable=True),
    sa.Column('mint_term_id', sa.Integer(), nullable=True),
    sa.Column('denomination_term_id', sa.Integer(), nullable=True),
    sa.Column('dynasty_term_id', sa.Integer(), nullable=True),
    sa.Column('grading_state', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('grade_service', sa.String(length=20), nullable=True),
    sa.Column('certification_number', sa.String(length=50), nullable=True),
    sa.Column('strike_quality', sa.String(length=20), nullable=True),
    sa.Column('surface_quality', sa.String(length=20), nullable=True),
    sa.Column('acquisition_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acquisition_currency', sa.String(length=3), nullable=True),
    sa.Column('acquisition_source', sa.String(length=100), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('denomination', sa.String(length=50), nullable=True),
    sa.Column('portrait_subject', sa.String(length=100), nullable=True),
    sa.Column('obverse_legend', sa.String(length=500), nullable=True),
    sa.Column('obverse_description', sa.String(length=500), nullable=True),
    sa.Column('reverse_legend', sa.String(length=500), nullable=True),
    sa.Column('reverse_description', sa.String(length=500), nullable=True),
    sa.Column('exergue', sa.String(length=100), nullable=True),
    sa.Column('issue_status', sa.String(length=20), nullable=False),
    sa.Column('specific_gravity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('obverse_die_id', sa.String(length=50), nullable=True),
    sa.Column('reverse_die_id', sa.String(length=50), nullable=True),
    sa.Column('secondary_treatments', sa.Text(), nullable=True),
    sa.Column('find_spot', sa.String(length=255), nullable=True),
    sa.Column('find_date', sa.Date(), nullable=True),
    sa.Column('obverse_legend_expanded', sa.Text(), nullable=True),
    sa.Column('reverse_legend_expanded', sa.Text(), nullable=True),
    sa.Column('historical_significance', sa.Text(), nullable=True),
    sa.Column('catalog_description', sa.Text(), nullable=True),
    sa.Column('condition_observations', sa.Text(), nullable=True),
    sa.Column('llm_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('llm_analysis_sections', sa.Text(), nullable=True),
    sa.Column('llm_suggested_references', sa.Text(), nullable=True),
    sa.Column('llm_suggested_rarity', sa.Text(), nullable=True),
    sa.Column('llm_suggested_design', sa.Text(), nullable=True),
    sa.Column('llm_suggested_attribution', sa.Text(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('reign_start', sa.Integer(), nullable=True),
    sa.Column('reign_end', sa.Integer(), nullable=True),
    sa.Column('dating_certainty', sa.String(length=20), nullable=True),
    sa.Column('is_circa', sa.Boolean(), nullable=True),
    sa.Column('provenance_notes', sa.Text(), nullable=True),
    sa.Column('surface_issues', sa.Text(), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('series', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('officina', sa.String(length=20), nullable=True),
    sa.Column('obverse_symbols', sa.String(length=255), nullable=True),
    sa.Column('reverse_symbols', sa.String(length=255), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('rarity_notes', sa.Text(), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('toning_description', sa.Text(), nullable=True),
    sa.Column('eye_appeal', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('obverse_iconography', sa.Text(), nullable=True),
    sa.Column('reverse_iconography', sa.Text(), nullable=True),
    sa.Column('control_marks', sa.Text(), nullable=True),
    sa.Column('mintmark', sa.String(length=50), nullable=True),
    sa.Column('field_marks', sa.Text(), nullable=True),
    sa.Column('die_state', sa.String(length=20), nullable=True),
    sa.Column('die_match_notes', sa.Text(), nullable=True),
    sa.Column('moneyer', sa.String(length=100), nullable=True),
    sa.Column('edge_type', sa.String(length=30), nullable=True),
    sa.Column('edge_inscription', sa.String(length=255), nullable=True),
    sa.Column('attribution_confidence', sa.String(length=20), nullable=True),
    sa.Column('attribution_notes', sa.Text(), nullable=True),
    sa.Column('cleaning_history', sa.Text(), nullable=True),
    sa.Column('conservation_notes', sa.Text(), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_value_date', sa.Date(), nullable=True),
    sa.CheckConstraint('die_axis >= 0 AND die_axis <= 12', name='check_die_axis_range'),
    sa.ForeignKeyConstraint(['denomination_term_id'], ['vocab_terms.id'], ),
    sa.ForeignKeyConstraint(['dynasty_term_id'], ['vocab_terms.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.ForeignKeyConstraint(['issuer_term_id'], ['vocab_terms.id'], ),
    sa.ForeignKeyConstraint(['mint_id'], ['mints.id'], ),
    sa.ForeignKeyConstraint(['mint_term_id'], ['vocab_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coins_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coins_v2_acquisition_date'), ['acquisition_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_denomination'), ['denomination'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_grading_state'), ['grading_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_issue_status'), ['issue_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_metal'), ['metal'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_obverse_die_id'), ['obverse_die_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_portrait_subject'), ['portrait_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_reverse_die_id'), ['reverse_die_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coins_v2_year_start'), ['year_start'], unique=False)

    op.create_table('die_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('die_side', sa.String(length=20), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('mint_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.ForeignKeyConstraint(['mint_id'], ['mints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('die_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_die_groups_id'), ['id'], unique=False)

    op.create_table('issuer_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('normalized_form', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issuer_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuer_aliases_normalized_form'), ['normalized_form'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('series_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('canonical_vocab_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('target_count IS NULL OR target_count > 0', name='check_target_count'),
    sa.ForeignKeyConstraint(['canonical_vocab_id'], ['vocab_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_slug'), ['slug'], unique=True)

    op.create_table('auction_data_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('sale_name', sa.String(length=255), nullable=True),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('source_lot_id', sa.String(length=50), nullable=True),
    sa.Column('hammer_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimate_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimate_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('issuer', sa.String(length=100), nullable=True),
    sa.Column('mint', sa.String(length=100), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('weight_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('diameter_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('die_axis', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('additional_images', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auction_data_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_data_v2_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_data_v2_url'), ['url'], unique=True)

    op.create_table('coin_images_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_images_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_images_v2_id'), ['id'], unique=False)

    op.create_table('coin_monograms',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('monogram_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.ForeignKeyConstraint(['monogram_id'], ['monograms.id'], ),
    sa.PrimaryKeyConstraint('coin_id', 'monogram_id')
    )
    op.create_table('coin_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('reference_type_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('plate_coin', sa.Boolean(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('variant_notes', sa.String(length=255), nullable=True),
    sa.Column('page', sa.String(length=20), nullable=True),
    sa.Column('plate', sa.String(length=30), nullable=True),
    sa.Column('note_number', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.ForeignKeyConstraint(['reference_type_id'], ['reference_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_references_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_references_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_references_reference_type_id'), ['reference_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_references_source'), ['source'], unique=False)

    op.create_table('coin_vocab_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('vocab_term_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.ForeignKeyConstraint(['vocab_term_id'], ['vocab_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_vocab_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_vocab_assignments_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_vocab_assignments_status'), ['status'], unique=False)

    op.create_table('die_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('die_group_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.ForeignKeyConstraint(['die_group_id'], ['die_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('die_group_id', 'coin_id', name='uq_die_group_member')
    )
    with op.batch_alter_table('die_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_die_group_members_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_die_group_members_die_group_id'), ['die_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_die_group_members_id'), ['id'], unique=False)

    op.create_table('die_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_a_id', sa.Integer(), nullable=False),
    sa.Column('coin_b_id', sa.Integer(), nullable=False),
    sa.Column('die_side', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('identified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_a_id'], ['coins_v2.id'], ),
    sa.ForeignKeyConstraint(['coin_b_id'], ['coins_v2.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_a_id', 'coin_b_id', 'die_side', name='uq_die_link_pair_side')
    )
    with op.batch_alter_table('die_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_die_links_coin_a_id'), ['coin_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_die_links_coin_b_id'), ['coin_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_die_links_id'), ['id'], unique=False)

    op.create_table('series_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot_number > 0', name='check_slot_number'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'slot_number', name='uq_series_slot_number')
    )
    with op.batch_alter_table('series_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_slots_status'), ['status'], unique=False)

    op.create_table('provenance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('auction_house', sa.String(length=100), nullable=True),
    sa.Column('sale_series', sa.String(length=50), nullable=True),
    sa.Column('sale_number', sa.String(length=20), nullable=True),
    sa.Column('lot_number', sa.String(length=20), nullable=True),
    sa.Column('catalog_reference', sa.String(length=200), nullable=True),
    sa.Column('hammer_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buyers_premium_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('dealer_name', sa.String(length=100), nullable=True),
    sa.Column('collection_name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('receipt_available', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('auction_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_data_id'], ['auction_data_v2.id'], ),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provenance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provenance_events_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provenance_events_id'), ['id'], unique=False)

    op.create_table('series_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['series_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_memberships')
    with op.batch_alter_table('provenance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provenance_events_id'))
        batch_op.drop_index(batch_op.f('ix_provenance_events_coin_id'))

    op.drop_table('provenance_events')
    with op.batch_alter_table('series_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_slots_status'))

    op.drop_table('series_slots')
    with op.batch_alter_table('die_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_die_links_id'))
        batch_op.drop_index(batch_op.f('ix_die_links_coin_b_id'))
        batch_op.drop_index(batch_op.f('ix_die_links_coin_a_id'))

    op.drop_table('die_links')
    with op.batch_alter_table('die_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_die_group_members_id'))
        batch_op.drop_index(batch_op.f('ix_die_group_members_die_group_id'))
        batch_op.drop_index(batch_op.f('ix_die_group_members_coin_id'))

    op.drop_table('die_group_members')
    with op.batch_alter_table('coin_vocab_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_vocab_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_coin_vocab_assignments_coin_id'))

    op.drop_table('coin_vocab_assignments')
    with op.batch_alter_table('coin_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_references_source'))
        batch_op.drop_index(batch_op.f('ix_coin_references_reference_type_id'))
        batch_op.drop_index(batch_op.f('ix_coin_references_id'))
        batch_op.drop_index(batch_op.f('ix_coin_references_coin_id'))

    op.drop_table('coin_references')
    op.drop_table('coin_monograms')
    with op.batch_alter_table('coin_images_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_images_v2_id'))

    op.drop_table('coin_images_v2')
    with op.batch_alter_table('auction_data_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_data_v2_url'))
        batch_op.drop_index(batch_op.f('ix_auction_data_v2_id'))

    op.drop_table('auction_data_v2')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_slug'))

    op.drop_table('series')
    with op.batch_alter_table('issuer_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuer_aliases_normalized_form'))

    op.drop_table('issuer_aliases')
    with op.batch_alter_table('die_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_die_groups_id'))

    op.drop_table('die_groups')
    with op.batch_alter_table('coins_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coins_v2_year_start'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_reverse_die_id'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_portrait_subject'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_obverse_die_id'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_metal'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_issue_status'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_id'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_grading_state'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_denomination'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_category'))
        batch_op.drop_index(batch_op.f('ix_coins_v2_acquisition_date'))

    op.drop_table('coins_v2')
    with op.batch_alter_table('vocab_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_terms_vocab_type'))

    op.drop_table('vocab_terms')
    with op.batch_alter_table('vocab_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_cache_expires_at'))

    op.drop_table('vocab_cache')
    with op.batch_alter_table('reference_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_types_id'))

    op.drop_table('reference_types')
    with op.batch_alter_table('monograms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monograms_label'))
        batch_op.drop_index(batch_op.f('ix_monograms_id'))

    op.drop_table('monograms')
    with op.batch_alter_table('mints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mints_nomisma_id'))
        batch_op.drop_index(batch_op.f('ix_mints_canonical_name'))

    op.drop_table('mints')
    with op.batch_alter_table('issuers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuers_nomisma_id'))
        batch_op.drop_index(batch_op.f('ix_issuers_canonical_name'))

    op.drop_table('issuers')
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_id'))

    op.drop_table('enrichment_jobs')
    # ### end Alembic commands ###
